apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web-server
  labels:
    app: nginx-web-server
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-web-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-web-server
    spec:
      containers:
        - image: narothamsai/nginx-web-server
          imagePullPolicy: Always
          name: nginx-web-server
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-web-server
  labels:
    app: nginx-web-server
spec:
  type: LoadBalancer
  selector:
    app: nginx-web-server
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
